export const categories = [
    { value: 'uncategorized', label: 'Select a Category' },
    { value: 'news', label: 'News' },
    { value: 'regional_news', label: 'Regional News' },
    { value: 'global_news', label: 'Global News' },
    { value: 'industry_updates', label: 'Industry Updates' },
    { value: 'press_releases', label: 'Press Releases' },
    { value: 'analysis', label: 'Analysis' },
    { value: 'market_analysis', label: 'Market Analysis' },
    { value: 'policy_regulation', label: 'Policy & Regulation' },
    { value: 'technology_trends', label: 'Technology Trends' },
    { value: 'expert_opinions', label: 'Expert Opinions' },
    { value: 'features', label: 'Features' },
    { value: 'personality_of_the_week_feature', label: 'Personality of the Week' },
    { value: 'case_studies', label: 'Case Studies' },
    { value: 'interviews', label: 'Interviews' },
    { value: 'special_editions', label: 'Special Editions' },
    { value: 'sectors', label: 'Sectors' },
    { value: 'oil_gas', label: 'Oil & Gas' },
    { value: 'renewable_energy', label: 'Renewable Energy' },
    { value: 'power_utilities', label: 'Power & Utilities' },
    { value: 'nuclear_energy', label: 'Nuclear Energy' },
    { value: 'energy_efficiency', label: 'Energy Efficiency' },
    { value: 'regions', label: 'Regions' },
    { value: 'middle_east', label: 'Middle East' },
    { value: 'north_africa', label: 'North Africa' },
    { value: 'sub_saharan_africa', label: 'Sub-Saharan Africa' },
    { value: 'gcc_countries', label: 'GCC Countries' },
    { value: 'energy_transition', label: 'Energy Transition' },
    { value: 'decarbonization_strategies', label: 'Decarbonization Strategies' },
    { value: 'renewable_integration', label: 'Renewable Integration' },
    { value: 'carbon_capture_storage', label: 'Carbon Capture & Storage' },
    { value: 'sustainable_energy_innovations', label: 'Sustainable Energy Innovations' },
    { value: 'green_financing', label: 'Green Financing' },
  ];